Alterations to ggplot2 lesson by Lindsay
UofTCoders/studyGroup pull request #243
Opened 2017-02-14 16:59 UTC by lcoome

Added new lesson, figures, interative html plot, R code

2017-02-14 19:32 UTC, lwjohnst86 requested changes

2017-02-14 19:32 UTC, lwjohnst86 commented on lessons/r/ggplot2/Lindsayggplot2.Rmd
> +    variant: markdown_github
These three lines can be changed to just `output: github_document`

2017-02-14 19:32 UTC, lwjohnst86 commented on lessons/r/ggplot2/Lindsayggplot2.Rmd
> +* ##### Lesson Topic: Plotting in R using ggplot2
Please remove the `####` from both lines

2017-02-14 19:32 UTC, lwjohnst86 commented on lessons/r/ggplot2/Lindsayggplot2.Rmd
> +* ##### Lesson Topic: Plotting in R using ggplot2
Also include the link to the github repo material (https://github.com/UofTCoders/studyGroup/tree/gh-pages/lessons/r/ggplot2)

2017-02-14 19:32 UTC, lwjohnst86 commented on lessons/r/ggplot2/Lindsayggplot2.Rmd
> +---
Rename this file to be `lesson.Rmd`. You can write over Sarah's lesson file.

2017-02-14 19:32 UTC, lwjohnst86 commented on lessons/r/ggplot2/Lindsayggplot2.md
> +INTRODUCTION TO GGPLOT2
This file will be changed after you rename the other file to `lesson.Rmd`.

2017-02-14 19:32 UTC, lwjohnst86 commented on lessons/r/ggplot2/Lindsayggplot2.Rmd
> +
You can add this code chunk above:

    ```{r, echo=FALSE}
    knitr::opt_chunk$set(fig.path = 'figure/')
    ```

Then re-knit the file.

2017-02-14 19:32 UTC, lwjohnst86 commented on lessons/r/ggplot2/Lindsayggplot2_files/figure-markdown_github/Imagefiles.Rmd
> +##Contains all image files
These files will be renamed after including the above code chunk (`knitr::opt_chunk$set(fig.path = 'figure/')`)

2017-02-14 19:32 UTC, lwjohnst86 commented on lessons/r/ggplot2/Lindsayggplot2_files/figure-markdown_github/Imagefiles.Rmd
> +##Contains all image files
You may likely need to delete all of these figure files.

2017-02-14 21:40 UTC, QuLogic commented on lessons/r/ggplot2/Lindsayggplot2.Rmd
> +ggplot2 is meant to be an implementation of the Grammar of Graphics, hence gg-plot. The basic notion is that there is a grammar to the composition of graphical components in statistical graphics, and
direcly -> directly

2017-02-14 21:40 UTC, QuLogic commented on lessons/r/ggplot2/Lindsayggplot2.Rmd
> +[r graph gallery for inspiration (not just limited to ggplot2 graphs)](http://www.r-graph-gallery.com/all-graphs/)
https

2017-02-15 19:58 UTC, closed without merging

2017-02-15 21:35 UTC, QuLogic commented
32 messages? Wow, working on the GitHub web interface sure is annoying...

2017-02-15 21:59 UTC, lcoome commented
Agreed
________________________________
From: Elliott Sales de Andrade <notifications@github.com>
Sent: February 15, 2017 4:35:58 PM
To: UofTCoders/studyGroup
Cc: Lindsay Coome; State change
Subject: Re: [UofTCoders/studyGroup] Alterations to ggplot2 lesson by Lindsay (#243)


32 messages? Wow, working on the GitHub web interface sure is annoying...

—
You are receiving this because you modified the open/close state.
Reply to this email directly, view it on GitHub<https://github.com/UofTCoders/studyGroup/pull/243#issuecomment-280146845>, or mute the thread<https://github.com/notifications/unsubscribe-auth/AMwunYdmHh3_Vwo2XWYYnSRAV9d-VFU0ks5rc2--gaJpZM4MAusO>.