updated executive list, added new members
UofTCoders/studyGroup pull request #343
Opened 2018-02-09 12:07 UTC by lwjohnst86

@aays @SaraMahallati @nsahin Let me know if this is correct. Otherwise I will merge in.

@mbonsma @linamnt Do you want me to change your positions as well?

@lcoome Since @mbonsma is now the Special Events Coordinator, what is your position? I can't recall what we discussed.

@joelostblom Do you have a new title or you share with @aays?

2018-02-09 13:17 UTC, joelostblom commented
Maybe put me as technical admin as well (we need a fancier name for it to embellish our resumes...)?  And can you change "IBBME" to "Biomedical Engineering"?

2018-02-09 20:55 UTC, QuLogic commented
Do we need to wait for elections to make this official?

2018-02-09 23:04 UTC, lwjohnst86 commented
@QuLogic good question. At least for my position, you don't ... since I'm not there! :P We can put this PR on hold if need be until then. And @joelostblom what about Technical Specialist or Technical Support Specialist or Webmaster or Web Administrator or Technical Operations Officer or Support Specialist...? Thoughts @QuLogic since you also share the title.

2018-05-08 16:48 UTC, linamnt commented
Now elections are over, we can also add @mbonsma for Special Events Coordinator, @lcoome Marketing and Social Media Coordinator? @joelostblom any final requests for your role title?

2018-05-09 21:07 UTC, lwjohnst86 commented
So all are as included in the admin file? @linamnt as president, etc? @QuLogic Still technical admin?

2018-05-10 02:37 UTC, QuLogic requested changes

2018-05-10 02:37 UTC, QuLogic commented on _data/admin.yml
> +  github: SaraMahallati
@SaraMati

2018-05-10 10:33 UTC, merged